### PR TITLE
Implemented 9 new functions

### PR DESCRIPTION
**Pull request by Barabazs**
I've added 2 new functions to:

- Mark an article as unsaved
- Get the content from an entryId

### CODE REVIEW

**Comment by Barabazs** [comment]
Added 7 functions

- get_categories
- get_sorted_categories
- change_category_label
- delete_category
- get_user_preferences
- update_user_preferences
- delete_user_preference

**Comment by Barabazs** [comment]
@axsapronov

**Comment by axsapronov** [comment]
Sorry for long delay.
I missed github notification about PR.

**Comment by axsapronov** [comment]
Thanks for PR.

**Comment by axsapronov** [comment]
Bump version in PyPi

**Pull request merged**
